### ISSUE TITLE
このワークフロー作ってもいいかも

### ISSUE THREAD

**Issue by blendthink** [blendthink/blendthink#1]
Hi @selfagency 

I'm not sure about adding that functionality into this action itself, but what you want to do is very easy to achieve anyway with one extra workflow step to delete the comment.

Change this to suit your use case, but something like this should work.

```yml
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Build output

    - if: steps.fc.outputs.comment-id != ''
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.deleteComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            comment_id: ${{ steps.fc.outputs.comment-id }}
          })

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Build output
          ${{ steps.build.outputs.build-log }}
```

_Originally posted by @peter-evans in https://github.com/peter-evans/create-or-update-comment/issues/110#issuecomment-1086997843_
